### ISSUE TITLE
Does not work with the current jogl version

### ISSUE THREAD

**Issue by chkais** [bytedeco/javacv#166]
When starting an application with jogl >= 3.0.0 the following error appears:
```
java.lang.NoClassDefFoundError: javax/media/opengl/GLEventListener
```
Unfortunatly there was an api change in jogl 3.0.0. The GLEventListener Class moved from javax.media to com.jogamp.opengl  (an I think some other classes too). 
To get javacv to work with jogl, one needs jogl version 2.4.

**Comment by saudet** [comment]
I haven't kept up to date with that yes. Which class are you using from
JavaCV?

**Comment by chkais** [comment]
Hi Samuel,

At first I want to thank you for your great work.

I'm using the GLCanvasFrame. If you want I can Check out the Sourcecode and
make a pull request with the fix.

Regards,
Chris
Am 26.06.2015 01:47 schrieb "Samuel Audet" <notifications@github.com>:

**Comment by saudet** [comment]
Sure, if you could update the pom.xml file too, that would be great! Thanks

**Comment by chkais** [comment]
No Problem,
I will do it on the weekend - busy at work today.

Best,
Chris
 Am 26.06.2015 07:04 schrieb "Samuel Audet" <notifications@github.com>:

**Comment by saudet** [comment]
Thanks, looking forward to your contribution!

**Comment by chkais** [comment]
Hi, 
I'm sorry I am late. My spare time gets less and lesser :/ - should I update just the Pom with the working dependencies or try to fix the code so it runs with the current version? 

I hope I will find the time to look at it at the weekend. If someone else wants to fix it, he / she should go ahead :).

Best,
Chris

**Comment by saudet** [comment]
Yes, fix the code, of course. Thank you!

**Comment by saudet** [comment]
FYI, I've made the update in this commit: https://github.com/bytedeco/javacv/commit/c6d36d0ddab81ee2277a122c86d5da15bba21718

**Comment by saudet** [comment]
Fixed in version 1.1. Thanks for reporting!
