### ISSUE TITLE
FaceRecognizer the number of samples must be the same number of labels

### ISSUE THREAD

**Issue by marcosbontempo** [bytedeco/javacv#562]
Hello,

I'm using JavaCV version 0.9 in Android to perform Face Recognition. Here is my code:

```
        imageFiles = directoryApp.listFiles(pngFilter);

        opencv_core.MatVector images = new opencv_core.MatVector(imageFiles.length);
        opencv_core.Mat labels = new opencv_core.Mat(imageFiles.length, 1, opencv_core.CV_32SC1);

        for(int l=0; l < imageFiles.length; l++)
        {
                opencv_core.Mat img = opencv_highgui.imread(imageFiles[l].getAbsolutePath(), opencv_highgui.CV_LOAD_IMAGE_GRAYSCALE);
                int label = Integer.parseInt(imageFiles[l].getName().split("\\-")[0]);
                images.put(l, img);
                opencv_core.Mat labelMat = new opencv_core.Mat(label,1,opencv_core.CV_32SC1);
                labels.put(labelMat);
        }

        faceRecognizer = opencv_contrib.createLBPHFaceRecognizer();
        faceRecognizer.train(images, labels);
```

It returns this error when training:

FATAL EXCEPTION: Thread-271
Process: org.opencv.samples.facedetect, PID: 20107
java.lang.RuntimeException: /home/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/android-arm/opencv-2.4.9/modules/contrib/src/facerec.cpp:791: error: (-5) The number of samples (src) must equal the number of labels (labels). Was len(samples)=2, len(labels)=0. in function void cv::LBPH::train(cv::InputArrayOfArrays, cv::InputArray, bool)

I think the way I'm inserting the labels is wrong. The faceRecognizer.train() function only accepts the labels argument as a Mat, but in other implementations it also accepts as a integer array.

How can I insert the labels so the object have the same size of the number of samples? Why the length of the Mat is 0 if I inserted some labels?

Any tip will be very helpful,

Thanks

**Comment by saudet** [comment]
Please try to upgrade fo JavaCV 1.2 and let me know if you encounter the same issue. Thank you

**Comment by saudet** [comment]
Given the lack of feedback, I am assuming this works fine in JavaCV 1.2 (or 1.3).

**Comment by matthewcodes** [comment]
This is still happening in v1.3

> OpenCV Error: Bad argument (The number of samples (src) must equal the number of labels (labels). Was len(samples)=891, len(labels)=0.) in train, file /Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv_contrib-3.1.0/modules/face/src/lbph_faces.cpp, line 359
> 
> java.lang.RuntimeException: /Users/saudet/projects/bytedeco/javacpp-presets/opencv/cppbuild/macosx-x86_64/opencv_contrib-3.1.0/modules/face/src/lbph_faces.cpp:359: error: (-5) The number of samples (src) must equal the number of labels (labels). Was len(samples)=891, len(labels)=0. in function train
> 
> 
> at org.bytedeco.javacpp.opencv_face$FaceRecognizer.train(Native Method)

**Comment by saudet** [comment]
If you're looking into setting elements of `labels`, try to use an Indexer:
http://bytedeco.org/news/2014/12/23/third-release/
