### ISSUE TITLE
Crash app when create video

### ISSUE THREAD

**Issue by newstarbka** [bytedeco/javacv#590]
It's work fine on Sony Experia 4.4.4 but crash on Google nexus 4.4.4 and 4.3. The log cat below, please show me some advice

 Caused by: java.lang.NoClassDefFoundError: java.lang.ClassNotFoundException: org.bytedeco.javacpp.avutil
                                                                      at org.bytedeco.javacpp.Loader.load(Loader.java:590)
                                                                      at org.bytedeco.javacpp.Loader.load(Loader.java:530)
                                                                      at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2819)
                                                                      at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:391)
                                                                      at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:385)

**Comment by saudet** [comment]
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29

**Comment by newstarbka** [comment]
I'm just using Gradle  to import javacv, it's not the manual installation. And after add more code from your recommended link, it show error : "cannot resolve symbol ReLinker". So what should I do ?

**Comment by newstarbka** [comment]
Follow your recommended link and my error log above. What is the library that I need to ReLinker. That's 
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_core");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_core");
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_imgcodecs");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_imgcodecs");
ReLinker.log(logger).recursively().loadLibrary(context, "jniopencv_imgproc");
ReLinker.log(logger).recursively().loadLibrary(context, "opencv_imgproc");
